/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synthbot_audioplugin_vst_vst2_JVstHost24 */

#ifndef _Included_com_synthbot_audioplugin_vst_vst2_JVstHost24
#define _Included_com_synthbot_audioplugin_vst_vst2_JVstHost24
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_audioplugin_vst_vst2_JVstHost24
 * Method:    processDoubleReplacing
 * Signature: ([Ljavax/sound/midi/ShortMessage;[[D[[DIJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_vst2_JVstHost24_processDoubleReplacing
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jint, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_vst2_JVstHost24
 * Method:    canDoubleReplacing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_vst2_JVstHost24_canDoubleReplacing
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
