/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synthbot_audioplugin_vst_vst2_JVstHost23 */

#ifndef _Included_com_synthbot_audioplugin_vst_vst2_JVstHost23
#define _Included_com_synthbot_audioplugin_vst_vst2_JVstHost23
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_audioplugin_vst_vst2_JVstHost23
 * Method:    startProcess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_vst2_JVstHost23_startProcess
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_vst2_JVstHost23
 * Method:    stopProcess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_vst2_JVstHost23_stopProcess
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
