/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synthbot_audioplugin_vst_JVstHost */

#ifndef _Included_com_synthbot_audioplugin_vst_JVstHost
#define _Included_com_synthbot_audioplugin_vst_JVstHost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    loadPlugin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_loadPlugin
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    unloadPlugin
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_unloadPlugin
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    processReplacing
 * Signature: ([[F[[FIIIJJJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_processReplacing
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    setParameter
 * Signature: (IFJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_setParameter
  (JNIEnv *, jobject, jint, jfloat, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getParameter
 * Signature: (IJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getParameter
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getParameterName
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getParameterName
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getParameterDisplay
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getParameterDisplay
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getParameterLabel
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getParameterLabel
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getEffectName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getEffectName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getVendorName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getVendorName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getProductString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getProductString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    numParameters
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_numParameters
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    numInputs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_numInputs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    numOutputs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_numOutputs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    numPrograms
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_numPrograms
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    setSampleRate
 * Signature: (FJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_setSampleRate
  (JNIEnv *, jobject, jfloat, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    setBlockSize
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_setBlockSize
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    suspend
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_suspend
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    resume
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_resume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    setMidiEvents
 * Signature: ([Ljavax/sound/midi/ShortMessage;J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_setMidiEvents
  (JNIEnv *, jobject, jobjectArray, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getProgramName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getProgramName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    setProgramName
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_setProgramName
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getProgram
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getProgram
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    setProgram
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_setProgram
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    hasEditor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_hasEditor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    canReplacing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_canReplacing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    acceptsProgramsAsChunks
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_acceptsProgramsAsChunks
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getChunk
 * Signature: (IJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getChunk
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    setChunk
 * Signature: (I[BJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_setChunk
  (JNIEnv *, jobject, jint, jbyteArray, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    isSynth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_isSynth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    setBypass
 * Signature: (ZJ)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_setBypass
  (JNIEnv *, jobject, jboolean, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    canDoBypass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_canDoBypass
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    producesSoundInStop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_producesSoundInStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    openEditor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_openEditor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    closeEditor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_closeEditor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    editIdle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_editIdle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getUniqueId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getUniqueId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getVstVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getVstVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    startProcess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_startProcess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    stopProcess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_stopProcess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_synthbot_audioplugin_vst_JVstHost
 * Method:    getTailSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_audioplugin_vst_JVstHost_getTailSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
